### ISSUE TITLE
Install error rlang

### ISSUE THREAD

**Issue by kimnewzealand** [yutannihilation/ggsflabel#1]
Hi there 

I get the following error message when trying to install from GitHub. I am using Windows R version 3.5.1

ERROR: dependency 'rlang' is not available for package 'ggsflabel'
* removing 'C:/Users/Home/Documents/R/win-library/3.5/ggsflabel'
In R CMD INSTALL
Installation failed: Command failed (1)

It is possible to fix by installing rlang R package from CRAN

**Comment by yutannihilation** [comment]
Can you install rlang in a fresh session?

```r
install.packages("rlang")
```

Anyway, I'm closing this because it seems not the problem of ggsflabel. You might get better answers on https://community.rstudio.com/. Thanks!

**Comment by kimnewzealand** [comment]
no problem, it minor thing. I thought to raise it in case it can be installed during the ggsflabel package installation.

Thanks again for the package.
