### ISSUE TITLE
cant install 0.0.1

### ISSUE THREAD

**Issue by danielreispereira** [yutannihilation/ggsflabel#3]
devtools::install_github("yutannihilation/ggsflabel")

✓  checking for file ‘/private/var/folders/l6/tsm9k491581_htmv56b_df280000gn/T/RtmpWlSD8h/remotes10a21704c6739/yutannihilation-ggsflabel-a489481/DESCRIPTION’ ...
─  preparing ‘ggsflabel’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ggsflabel_0.0.1.tar.gz’
   
* installing *source* package ‘ggsflabel’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘ggplot2’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘ggsflabel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ggsflabel’
Error: Failed to install 'ggsflabel' from GitHub:
  (converted from warning) installation of package ‘/var/folders/l6/tsm9k491581_htmv56b_df280000gn/T//RtmpWlSD8h/file10a21280d08c8/ggsflabel_0.0.1.tar.gz’ had non-zero exit status

**Comment by yutannihilation** [comment]
> Error: (converted from warning) package ‘ggplot2’ was built under R version 3.6.2
> Execution halted

This doesn't seem a problem on ggsflabel's side :) You can try reinstalling ggplot2. Note that ggplot2 now has `geom_sf_text()` so you probably don't need this package unless you need the other minor functionalities.
